name: CI

on:
  push:
    branches: [dev, feature/**]
  pull_request:
    branches: [dev, main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run format:check

      - name: Type check
        run: npm run type-check

      - name: Check unused exports
        run: npx ts-unused-exports tsconfig.json || true

      - name: Run tests
        run: npm run test

      - name: Build check
        run: npm run build

      - name: Notify on success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: ci-notifications
          SLACK_TITLE: CI Passed ✅
          SLACK_MESSAGE: 'All tests passed for ${{ github.repository }} on branch ${{ github.ref_name }}'
          SLACK_COLOR: good

      - name: Notify on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: ci-notifications
          SLACK_TITLE: CI Failed ❌
          SLACK_MESSAGE: 'Tests failed for ${{ github.repository }} on branch ${{ github.ref_name }}. Check the logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
          SLACK_COLOR: danger
